/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("EquipmentsObjectPageObjectPage journey");

        opaTest("Navigate to EquipmentsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheEquipmentsListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheEquipmentsListGenerated.onTable().iCheckRows();
            When.onTheEquipmentsListGenerated.onTable().iPressRow(0);

            Then.onTheEquipmentsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheEquipmentsObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheEquipmentsObjectPageGenerated.iPressSectionIconTabFilterButton("GeneralInformation");
            Then.onTheEquipmentsObjectPageGenerated.iCheckSection({ section: "GeneralInformation" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "equipmentId" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "name" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "location" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "status" });
            When.onTheEquipmentsObjectPageGenerated.iPressSectionIconTabFilterButton("MaintenanceRequests");
            Then.onTheEquipmentsObjectPageGenerated.iCheckSection({ section: "MaintenanceRequests" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});