/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintenanceRequestsObjectPageObjectPage journey");

        opaTest("Navigate to MaintenanceRequestsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheMaintenanceRequestsListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheMaintenanceRequestsListGenerated.onTable().iCheckRows();
            When.onTheMaintenanceRequestsListGenerated.onTable().iPressRow(0);

            Then.onTheMaintenanceRequestsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheMaintenanceRequestsObjectPageGenerated.iCheckSection({ section: "GeneralInformation" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "equipment_ID" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "title" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "description" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "priority" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "status" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "requester" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "approver" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "comment" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "approvedAt" });
            Then.onTheMaintenanceRequestsObjectPageGenerated.onForm({ section: "GeneralInformation" }).iCheckField({ property: "closedAt" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});