/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintenanceRequestsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheMaintenanceRequestsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheMaintenanceRequestsListGenerated.onFilterBar().iCheckFilterField("equipment_ID");
            Then.onTheMaintenanceRequestsListGenerated.onFilterBar().iCheckFilterField("title");
            Then.onTheMaintenanceRequestsListGenerated.onFilterBar().iCheckFilterField("priority");
            Then.onTheMaintenanceRequestsListGenerated.onFilterBar().iCheckFilterField("status");
            Then.onTheMaintenanceRequestsListGenerated.onFilterBar().iCheckFilterField("requester");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheMaintenanceRequestsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheMaintenanceRequestsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheMaintenanceRequestsListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheMaintenanceRequestsListGenerated.onTable().iCheckColumns(undefined, {"equipment_ID":{"header":"Equipment"},"title":{"header":"Title"},"priority":{"header":"Priority"},"status":{"header":"Status"},"requester":{"header":"Requester"},"approver":{"header":"Approver"},"approvedAt":{"header":"Approved At"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheMaintenanceRequestsListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheMaintenanceRequestsListGenerated.onTable().iCheckRows();

            When.onTheMaintenanceRequestsListGenerated.onTable().iPressRow(0);
            Then.onTheMaintenanceRequestsObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});