Get https://ca116195trial.it-cpitrial05-rt.cfapps.us10-001.hana.ondemand.com/http/businesspartners_clean
Authorization: Basic c2ItZmYzMmM1MjAtOTFmNy00NmEwLTk5NWItN2MzZjE5MzY4NTI2IWI2NzAwODd8aXQtcnQtY2ExMTYxOTV0cmlhbCFiMjY2NTU6MDZlZTQ1NWMtZGMwZC00ODdkLWIwOGQtMTVlM2RjZmIxZDYzJHZfbXo5aG5lWUoya2dHUDBBSmRWM1FiUldYUEQyQjlZNk9HdlVQT0RqckU9